# Generated by Django 4.2.1 on 2023-06-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('ac_no', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=200)),
            ],
        ),
    ]
