# Generated by Django 4.2.1 on 2023-06-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
