# Generated by Django 4.2.1 on 2023-07-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commen', '0003_customer'),
        ('customer', '0004_alter_order_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commen.customer'),
        ),
    ]
