# Generated by Django 4.2.1 on 2023-07-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
