# Generated by Django 4.2.1 on 2023-07-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_order_payment_id_order_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
