# Generated by Django 4.2.1 on 2023-06-20 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commen', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catg_name', models.CharField(verbose_name=200)),
                ('discription', models.CharField(verbose_name=400)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commen.seller')),
            ],
        ),
    ]
